### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/unmutedstories-com#5]
- [x] Google Analytics
- [x] Optimize images
- [ ] Run Lighthouse tests and fix issues
- [ ] Consider regular perf testing, perhaps with [this plugin](https://github.com/netlify-labs/netlify-plugin-lighthouse)
- [x] Add favicon
- [ ] Meta images should be sourced from S3
- [x] Test SEO/meta on every page

**Comment by seancdavis** [comment]
We're live and everything is going just fine for now. Considering this done.
